# Generated by Django 4.1.2 on 2024-07-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(default='https://ejemplo.com/imagen-default.jpg'),
        ),
    ]
